### ISSUE TITLE
Having issues in production

### ISSUE THREAD

**Issue by ngust** [WeTransfer/zip_tricks#48]
Hi,

I switched my app to use this gem for streaming large CSV files.  It works as expected in development but in production, I get an empty zip file.

I'm using AWS/Elastic Beanstalk for my production environment.  I'm guessing it has something to do with my nginx config or something.  Has anyone had similar issues?

**Comment by ngust** [comment]
FYI, here's my controller code

`  class WorkersController < ApplicationController
  include ActionController::Live # required for streaming
  include ZipTricks::RailsStreaming
  require 'csv'

def data_export
   ...
   params stuff
   ...
   zip_tricks_stream do |zip|
  zip.write_deflated_file('report1.csv') do |sink|
    CSV(sink) do |csv|
       lookup = { taken: "Date of Course", id: "Student ID", workname: 'Student Name', name: 'Employer Name', title: "Course Name", provider: "Course Provider", instructor: "Instructor", expiry: "Expiry Date" }
       csv << lookup.values
      @workers.find_each(batch_size: 20) do |work| 
        ...
        CSV code
        ...
            csv << lookup.keys.map { |attr| combo["#{attr}"] }
          end
      end
    end
  end
      if @qrparams
        @workers.find_each(batch_size: 20) do |work| 
            zip.write_deflated_file("#{work.firstname}-#{work.lastname}-#{work.id}-qrcode.png") do |sink|
             ...
             QR code
             ...
                sink << work.generate_qr.to_s
            end
        end
      end
        if params[:certs]
              @workers.find_each(batch_size: 20) do |work| 
                   ...
                   PDF CODE
                   ...
                    pdf.stylesheets << css
                     sink << pdf.to_pdf.to_s
                     end
              end
            work.certificates.each do |cert|
                  if cert.image && cert.image.file
                    ext = cert.image.file.extension.downcase
                      zip.write_deflated_file("#{work.firstname}-#{work.lastname}-#{cert.paperwork.title}-#{cert.id}.#{ext}") do |sink|
                          sink << cert.image.file.read
                    end
                  else
                  end
                end
          end
    end
     end ## Zip Loop
 end
end`

**Comment by julik** [comment]
Hi @ngust, glad you are using ZipTricks and thank you for reporting.

I believe the issue here might be that there is an error (or an exception) inside the loop/block that you are using to do the streaming. When that loop gets executed Rails has already sent out the status code of the response. and is not rendering an error page to show you what is going wrong. So if an error occurs during the streaming process it is possible that your download would be 0-size if the error occurs early enough. ZipTricks actually does a very tiny bit of buffering in a couple of places. What might be exacerbating your problem is that you probably do not know for sure whether nginx is buffering for you or not, but that is not important at this stage - what is important is for you to find a way to determine which exception happens in your controller.

Here is what I would recommend. First you need to try doing a request with `curl` against your actual production endpoint that generates the ZIP file, and see what response comes out (what are you receiving as a response body and what headers the server sends you). You can do it with `curl -v <your-url>`. The second thing which might be necessary in this case is actually looking at your Rails application log on the server - the response might not contain the error that occurred, but the Rails application log usually will. In addition using something like Sentry, NewRelic or Appsignal for capturing errors that occur in production can be extremely beneficial. Basically you need to find out why your controller bugs out without returning any data and at which stage. Normally if I get in trouble like this and I don't have any monitoring installed I would SSH into a server and `tail -F` the Rails production log.

**Comment by julik** [comment]
In terms of NGINX configuration we always set `X-Accel-Buffering` to `no` to prevent nginx from caching the response. This might be a suitable thing to mention in the README but I suspect this is not the issue you are having (you would receive a workable ZIP file, just a notch later).

**Comment by ngust** [comment]
I set up a simplified action on my controller to test this.  Similar to the code above but just only for CSVs with a set query.

Prior to the test action, I didn't see any errors in the production or development rails logs.  I don't see any errors now either.  There is a difference in the results of the curl test though.

Here is the result of using curl on my development server:
```
$ curl -v 127.0.0.1:3000/workers/data_export_test
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 3000 (#0)
> GET /workers/data_export_test HTTP/1.1
> Host: 127.0.0.1:3000
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/zip
< Cache-Control: no-cache
< X-Request-Id: 4299ee33-45ce-4343-a5fa-8465266aae30
< X-Runtime: 0.228082
< Transfer-Encoding: chunked
< 
PK*�M
       	report1.csvUT�[d���][s�:r~?���/I��q#�G�����>�]�3=�4,Q��3c�����ݜ!	�D��Ö��?���~�����"j͡����ᶨ�ѻ��c�XįTͯ�������������h�w�n�6���_�Ϗ����%��	3WIz�������b��z��e};l�v
            	��report1.csvUT�[d��PKB�
Written using ZipTricks 4.6.0
```
The zip file comes out as expected.  

Results are a little different on the production side:

$ curl -v http://[my server]/workers/data_export_test
*   Trying xxx.xxx.xxx.xxx...
* Connected to qrsafety.com (xxx.xxx.xxx.xxx) port 80 (#0)
> GET /workers/data_export_test HTTP/1.1
> Host: [my server]
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Cache-Control: max-age=0, private, must-revalidate
< Content-Type: application/zip
< Date: Fri, 03 Aug 2018 16:38:45 GMT
< ETag: W/"179b594c438a742e70ceda4a7e54455b"
< Server: nginx/1.12.1
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< X-Request-Id: e5ad7f84-34ea-4f90-8089-bde81799ed69
< X-Runtime: 0.112295
< X-XSS-Protection: 1; mode=block
< Content-Length: 50
< Connection: keep-alive
< 
* Connection #0 to host [my server] left intact
PKքM
      	report1.csvUT�[d�

The zip file does the same as before.  Corrupt file of 50 bytes.

I don't see errors in any of my logs, nginx, puma, etc.

**Comment by julik** [comment]
Can you try removing the `include ActionController::Live` and try to see what happens? It looks like the zip output stops when it should start outputting the first compressed file (you are getting one local header and nothing more).

**Comment by ngust** [comment]
OK, I removed `include ActionController::Live`
The download works now, however, it doesn't stream and on large datasets I get a 504 timeout error.  The whole reason I used Zip Tricks in the first place was to get around that and stream the files.

**Comment by ngust** [comment]
I got this working now.  It was due to the nginx config.
I added some changes to my nginx config file and now it's good to go.

I changed my location section from this:
```
  location / {
    proxy_pass http://my_app; # match the name of upstream directive which is defined above
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
```
to this:
```
  location / {
          proxy_pass http://my_app; # match the name of upstream directive which is defined above
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Connection '';
          proxy_http_version 1.1;
          chunked_transfer_encoding off;
          proxy_buffering off;
          proxy_cache off;
        }
```

I also turned `include ActionController::Live` back on.

Works like a charm now.

**Comment by julik** [comment]
Glad to hear you managed to get it to work 🎉 

I believe your problem was the `proxy_buffering` option, it is described here http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffering

That is the one that is possible to disable on a per-response basis using `X-Accel-Buffering` header set to `no`. I will mention this in the documentation of ZipTricks.

**Comment by ngust** [comment]
Thanks for the help.  Hopefully, this will help others who experience similar issues.
